Adiciona método que retorna um Optional ao obter o valor do enum por uma String
doitsa/doit-commons pull request #46
Opened 2021-02-04 00:32 UTC by luizalfredo23

2021-02-04 02:40 UTC, luizalfredo23 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[vet4u] Add new products from EDI 832 catalogs](https://trello.com/c/83s6bMtT/2465-vet4u-add-new-products-from-edi-832-catalogs)

2021-02-05 22:28 UTC, hprange requested changes

2021-02-05 22:28 UTC, hprange commented on src/main/java/br/com/doit/commons/lang/Enums.java
> +        }
@luizalfredo23 Eu sei que a gente só deveria se preocupar com performance quando a gente encontra um problema de performance. De qualquer forma, existe uma solução melhor para esse problema usando o método `Class.getEnumConstants()`. Dessa forma, não é preciso criar uma exceção, produzir todo um stack trace para depois você ignorar a exceção e retornar `null`. 😉

Meu argumento para mudar a implementação nesse caso é que este é um método bem genérico e não sabemos como os outros desenvolvedores vão utilizá-lo. Portanto, vale a pena fazer uma solução um pouco mais performática.

Dá uma olhada nesse guia para mais informações sobre como "examinar" enums.

https://docs.oracle.com/javase/tutorial/reflect/special/enumMembers.html

2021-02-05 22:28 UTC, hprange commented on src/main/java/br/com/doit/commons/lang/Enums.java
>          }
@luizalfredo23 mesma coisa aqui. Na verdade, você poderia implementar esse método com base no seu outro método e não precisaria do try/catch:

```java
return Optional.ofNullable(Enums.valueOfOrNull(type, field);
```

2021-02-23 00:20 UTC, hprange approved these changes

2021-03-31 21:09 UTC, merged